rango/mainapp/urls.py
from django.conf.urls import url
from mainapp import views

app_name = 'mainapp'

urlpatterns = [
    url(r'^add_category/$', views.add_category, name = 'add_category'),
    url(r'^(?P<category_name_slug>[\w\-]+)/$', views.category_detail, name = 'category_detail'),
    url(r'^(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name = 'add_page'),
]

rango/rango/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from mainapp import urls as mainurls
from rango import views
from mainapp import views as mainviews

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name = 'index'),
    url(r'^category/', include(mainurls)),
    url(r'^about/$', views.about, name = 'about'),
    url(r'^register/$', mainviews.register, name = 'register'),
    url(r'^login/$', mainviews.user_login, name = 'login'),
    url(r'^logout/$', mainviews.user_logout, name = 'logout'),
] + static(settings.MEDIA_URL,  document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

rango/mainapp/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length = 40, unique = True)
    views = models.PositiveIntegerField(default = 0)
    likes = models.PositiveIntegerField(default = 0)
    slug = models.SlugField(blank = True, unique = True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return '{}*{}[{}]'.format(self.name,self.views, self.likes)


class Page(models.Model):
    title = models.CharField(max_length = 40)
    views = models.PositiveIntegerField(default = 0)
    url = models.URLField()
    category = models.ForeignKey(Category, on_delete = models.CASCADE)

    def __str__(self):
        return '{}({})'.format(self.title, self.views)


class UserProfile(models.Model):
    """docstring for UserProfile."""
    user = models.OneToOneField(User)
    website = models.URLField(blank = True)
    picture = models.ImageField(upload_to='profile_images', blank = True)

    def __str__(self):
        return self.user.username

rango/mainapp/forms.py
from django import forms
from mainapp.models import Category, Page, UserProfile
from django.contrib.auth.models import User

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length = 40, help_text = 'Please enter the category name.')

    views = forms.IntegerField(widget = forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget = forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget = forms.HiddenInput(), required = False)

    class Meta:
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length = 40, help_text = 'Please enter the page title.')
    url = forms.URLField(max_length = 200, help_text = 'Please enter the url of the page.')

    views = forms.IntegerField(widget = forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not (url.startswith('http://') or url.startswith('https://')):
            url = 'http://' + url
            cleaned_data['url'] = url

            return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango/mainapp/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from mainapp.models import Category, Page
from mainapp.forms import CategoryForm, PageForm, UserForm, UserProfileForm

# Create your views here.

def category_detail(request, category_name_slug):
    category = get_object_or_404(Category, slug = category_name_slug)
    category.views = category.views + 1
    category.save()
    pages = Page.objects.filter(category = category)
    context = {'category' : category, 'pages' : pages}
    return render(request, 'mainapp/category_detail.html', context)


@login_required
def add_category(request):
    form = CategoryForm()
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
        else:
            print(form.errors)
    return render(request, 'mainapp/add_category.html', {'form' : form})


@login_required
def add_page(request, category_name_slug):
    category = get_object_or_404(Category, slug = category_name_slug)

    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            page = form.save(commit = False)
            page.category = category
            page.save()
            return redirect('mainapp:category_detail', category_name_slug = category_name_slug)
        else:
            print(form.errors)

    context = {'form':form, 'category':category}
    return render(request, 'mainapp/add_page.html', context)

def register(request):
    reged = False

    if request.method == 'POST':
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()
            reged = True
        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'mainapp/register.html',{
        'user_form': user_form,
        'profile_form': profile_form,
        'registered': reged,
    })


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username = username, password = password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Your Rango account is unactive.')
        else:
            print('Invalid login or password: {}  {}'.format(username, password))
            return HttpResponse('Invalid login or password.')
    else:
        return render(request, 'mainapp/login.html', {})

@login_required
def user_logout(request):
    logout(request)
    return redirect('index')

rango/rango/views.py
from django.shortcuts import render
from mainapp.models import Category, Page

# Create your views here.

def index(request):
    request.session.set_test_cookie()
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:10]
    context = {'categories' : category_list, 'pages' : page_list}
    return render(request, 'index.html', context)


def about(request):
    if request.session.test_cookie_worked():
        print('test cookie worked.')
        request.session.delete_test_cookie()
    context = {'author_name':'Tvoretc'}
    return render(request, 'about.html', context)

rango/mainapp/templates/mainapp/add_category.html
{% extends 'base.html' %}
{% block content %}
    <h2>Add new Category</h2>

    <form method="post">
      {% csrf_token %}
      {% for hidden in form.hidden_fields %}
        <p>{{ hidden }}</p>
      {% endfor %}

      {% for field in form.visible_fields %}
        <p>{{ field.error }}</p>
        <p>{{ field.help_text }}</p>
        <p>{{ field }}</p>
      {% endfor %}
      <input type="submit" value="Submit">
    </form>
{% endblock %}

rango/mainapp/templates/mainapp/add_page.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">
      {% csrf_token %}
      {% for hidden in form.hidden_fields %}
        <p>{{ hidden }}</p>
      {% endfor %}

      {% for field in form.visible_fields %}
        <p>{{ fleid.errors }}</p>
        <p>{{ field.help_text }}</p>
        <p>{{ field }}</p>
      {% endfor %}
      <input type="submit" value="Submit">
    </form>
{% endblock %}

rango/mainapp/templates/mainapp/category_detail.html
{% extends 'base.html' %}
{% block content %}
    <p>{{category.name}}</p>

    <p>views: {{category.views}}, likes: {{category.likes}}</p>
    <a href="{% url 'mainapp:add_page' category_name_slug=category.slug %}">Add new page</a><br>
    <h3>List of pages:</h3>
    {% for page in pages %}
      <p><a href="{{page.url}}">{{page}}</a></p>
    {% endfor %}
{% endblock %}

rango/mainapp/templates/mainapp/cats.html
<ul>
  {% if cats %}
    {% for c in cats %}
      {% if c == act_cat %}
        <strong><li> <a href="{% url 'mainapp:category_detail' c.slug %}">{{c.name}}</a> </li></strong>
      {% else %}
        <li> <a href="{% url 'mainapp:category_detail' c.slug %}">{{c.name}}</a> </li>
      {% endif %}
    {% endfor %}
  {% else %}
    <li> <strong>No category present</strong> </li>
  {% endif %}
</ul>

rango/mainapp/templates/mainapp/login.html
{% extends 'base.html' %}
{% block content %}
  <form action="{% url 'login' %}" method="post">
    {% csrf_token %}
    <input type="text" name="username" value="" size="50"><br>
    <input type="password" name="password" value="" size"50"><br>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

rango/mainapp/templates/mainapp/register.html
{% extends "base.html" %}
{% block content %}
  {% if registered %}
    <h2>Thank you for registration.</h2>
    <a href="{% url 'index' %}">back to home</a><br>
  {% else %}
    <h2>Register</h2>
    <form action="{% url 'register' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" value="Register">
    </form>
  {% endif %}
{% endblock %}

rango/templates/about.html
{% extends 'base.html' %}
{% block content %}
    <p>About page.</p>
    {{author_name}} is the author of this site.
{% endblock %}

rango/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Rango</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/master.css' %}">
    <!--script type="text/javascript" src="{% static 'js/jquery.js' %}"></script-->
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'index' %}">Rango</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home<span class="sr-only">(current)</span></a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'register' %}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
          {% endif %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'mainapp:add_category' %}">New Category</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    <div class="">
      {% block sidebar_block %}
        {% get_category_list category %}
      {% endblock %}
    </div>
    <div class="content">
      <div class="jumbotron">
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </body>
</html>

rango/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <img src="{% static 'images/rango.jpg' %}" alt=""><br>
    <p>Rango says...</p>
    <div>
      hey there, partner! <br \>
        <strong>{{boldmessage}}</strong><br \>
    </div>

    <a href="{% url 'mainapp:add_category' %}">add new category</a><br>
    <a href="{% url 'about' %}">about page</a><br>
    <p>Top 5 viewed categories</p>
    {% if categories %}
      {% for cat in categories %}
        <a href="{% url 'mainapp:category_detail' category_name_slug=cat.slug %}">{{cat}}</a><br>
      {% endfor %}
    {% else %}
      <p>No categories.</p>
    {% endif %}

    <h3>Top 10 viewed pages.</h3>
    {% if pages %}
      {% for page in pages %}
        <a href="{{page.url}}">{{page}}</a><br>
      {% endfor %}
    {% else %}
      <p>No pages.</p>
    {% endif %}
{% endblock %}